// vue-coingecko-api/src/App.vue
<template>
  <div class="container">
    <div class="row">
      <h1>Coin Market</h1>

      <input
        type="text"
        class="form-control bg-dark text-light rounded-0 border-0 my-4"
        placeholder="Search Coin"
        @keyup="searchCoin()"
        v-model="textSearch"
      />
      <table class="table table-dark">
        <thead>
          <tr>
            <th v-for="title in titles" :key="{ title }">{{ title }}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(coin, index) in filteredCoins" :key="coin.id">
            <td class="text-muted">{{ index + 1 }}</td>
            <td>
              <img :src="coin.image" style="width: 2rem" class="me-2" />
              <span>{{ coin.name }}</span
              ><span class="ms-2 text-uppercase text-muted">{{
                coin.symbol
              }}</span>
            </td>
            <td>${{ coin.current_price.toLocaleString() }}</td>
            <td
              :class="[
                coin.price_change_percentage_24h > 0
                  ? 'text-success'
                  : 'text-danger',
              ]"
            >
              {{ coin.price_change_percentage_24h.toLocaleString() }}%
            </td>
            <td>${{ coin.total_volume.toLocaleString() }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      coins: [],
      filteredCoins: [],
      titles: ["#", "Coin", "Price", "Price Change", "24H Volume"],
      textSearch: "",
    };
  },
  async mounted() {
    const res = await fetch(
      "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false"
    );

    const data = await res.json();

    this.coins = data;
    this.filteredCoins = data;
  },
  methods: {
    searchCoin() {
      console.log(this.textSearch);

      this.filteredCoins= this.coins.filter(
        (coin) =>
          coin.name.toLowerCase().includes(this.textSearch.toLowerCase()) ||
          coin.symbol.toLowerCase().includes(this.textSearch.toLowerCase())
      );
    },
  },
};
</script>

<style>
</style>

// svelte-coingecko-api/src/App.svelte
<script>
  import { onMount } from "svelte";

  let titles = ["#", "Coin", "Price", "Price Change", "24h Volume"];
  let coins = [];
  let filteredCoins = [];
  let ref = null;

  const loadCoins = async () => {
    const res = await fetch(
      "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false"
    );
    const data = await res.json();

    console.log(data);

    coins = data;
    filteredCoins = data;
  };
  loadCoins();

  const searchCoin = (value) => {
    console.log(value);
    filteredCoins = coins.filter((coin) =>
      coin.name
        .toLowerCase()
        .includes(
          value.toLowerCase() ||
            coin.symbol.toLowerCase().includes(value.toLowerCase())
        )
    );
  };

  onMount(() => {
    ref.focus();
  });
</script>

<div class="container">
  <div class="row">
    <h1>Coin Marker</h1>

    <input
      type="text"
      class="form-control bg-dark text-white rounded-0 border-0 my-4"
      placeholder="Search a coin"
      on:keyup={({ target: { value } }) => searchCoin(value)}
      bind:this={ref}
    />
    <table class="table table-dark">
      <thead>
        <tr>
          {#each titles as title}
            <th>{title}</th>
          {/each}
        </tr>
      </thead>
      <tbody>
        {#each filteredCoins as coin, i}
          <tr>
            <td class="text-muted">{i + 1}</td>
            <td>
              <img
                src={coin.image}
                alt={coin.name}
                style="width: 2rem;"
                class="img-fluid me-2"
              />
              <span>{coin.name}</span>
              <span class="text-muted text-uppercase ms-2">{coin.symbol}</span>
            </td>
            <td>${coin.current_price.toLocaleString()}</td>
            <td
              class={coin.price_change_percentage_24h > 0
                ? "text-success"
                : "text-danger"}
              >{coin.price_change_percentage_24h.toLocaleString()}%</td
            >
            <td>${coin.total_volume.toLocaleString()}</td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
</div>

<style>
</style>
