// vue-coingecko-api/src/App.vue
<template>
  <div class="container">
    <div class="row">
      <h1>Coin Market</h1>

      <input
        type="text"
        class="form-control bg-dark text-light rounded-0 border-0 my-4"
        placeholder="Search Coin"
        @keyup="searchCoin()"
        v-model="textSearch"
      />
      <table class="table table-dark">
        <thead>
          <tr>
            <th v-for="title in titles" :key="{ title }">{{ title }}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(coin, index) in filteredCoins" :key="coin.id">
            <td class="text-muted">{{ index + 1 }}</td>
            <td>
              <img :src="coin.image" style="width: 2rem" class="me-2" />
              <span>{{ coin.name }}</span
              ><span class="ms-2 text-uppercase text-muted">{{
                coin.symbol
              }}</span>
            </td>
            <td>${{ coin.current_price.toLocaleString() }}</td>
            <td
              :class="[
                coin.price_change_percentage_24h > 0
                  ? 'text-success'
                  : 'text-danger',
              ]"
            >
              {{ coin.price_change_percentage_24h.toLocaleString() }}%
            </td>
            <td>${{ coin.total_volume.toLocaleString() }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      coins: [],
      filteredCoins: [],
      titles: ["#", "Coin", "Price", "Price Change", "24H Volume"],
      textSearch: "",
    };
  },
  async mounted() {
    const res = await fetch(
      "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false"
    );

    const data = await res.json();

    this.coins = data;
    this.filteredCoins = data;
  },
  methods: {
    searchCoin() {
      console.log(this.textSearch);

      this.filteredCoins= this.coins.filter(
        (coin) =>
          coin.name.toLowerCase().includes(this.textSearch.toLowerCase()) ||
          coin.symbol.toLowerCase().includes(this.textSearch.toLowerCase())
      );
    },
  },
};
</script>

<style>
</style>

// angular-coingecko-api/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

interface Coin {
  id: string;
  name: string;
  symbol: string;
  image: string;
  current_price: number;
  price_change_percentage_24h: number;
  total_volume: number;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  coins: Coin[] = [];
  filteredCoins: Coin[] = [];
  titles: string[] = ['#', 'Coin', 'Price', 'Price Change', '24h Volume'];

  searchText = '';

  constructor(private http: HttpClient) {}

  searchCoin() {
    console.log(this.searchText);

    this.filteredCoins = this.coins.filter(
      (coin) =>
        coin.name.toLowerCase().includes(this.searchText.toLowerCase()) ||
        coin.symbol.toLowerCase().includes(this.searchText.toLowerCase())
    );
  }

  ngOnInit(): void {
    this.http
      .get<Coin[]>(
        'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false'
      )
      .subscribe(
        (res) => {
          console.log(res);
          this.coins = res;
          this.filteredCoins = res;
        },
        (err) => console.log(err)
      );
  }
}

<div class="container">
  <input
    type="text"
    class="form-control bg-dark text-light border-0 my-4 text-center rounded-0"
    placeholder="Search a coin"
    [(ngModel)]="searchText"
    (keyup)="searchCoin()"
  />
  <table class="table table-dark">
    <thead>
      <tr>
        <th *ngFor="let title of titles">{{ title }}</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let coin of filteredCoins; let i = index">
        <td class="text-muted">{{ i + 1 }}</td>
        <td>
          <img [src]="coin.image" alt="{{ coin.name }}" style="width: 2rem" />
          <span class="ms-3">{{ coin.name }}</span
          >&nbsp;
          <span class="text-muted text-uppercase ms-2">{{ coin.symbol }}</span>
        </td>
        <td>${{ coin.current_price.toLocaleString() }}</td>
        <td
          [ngClass]="
            coin.price_change_percentage_24h > 0
              ? 'text-success'
              : 'text-danger'
          "
        >
          {{ coin.price_change_percentage_24h.toLocaleString() }}
        </td>
        <td>{{ coin.total_volume.toLocaleString() }}</td>
      </tr>
    </tbody>
  </table>
</div>
